// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:elswhere/flavors.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return F.appFlavor == Flavor.dev ? android : androidProd;
      case TargetPlatform.iOS:
        return F.appFlavor == Flavor.dev ? ios : iosProd;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwWxZhjV4lcz3Fn-L1ieC7tlqSrqOeqRs',
    appId: '1:945515654091:android:a01d936d4e1eed1dc6a44e',
    messagingSenderId: '945515654091',
    projectId: 'elswhere-dev',
    storageBucket: 'elswhere-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtzBXYrhUfHTe7-aAb6H3JlSjHPQpoH9Q',
    appId: '1:945515654091:ios:3c7eac7532c5eac7c6a44e',
    messagingSenderId: '945515654091',
    projectId: 'elswhere-dev',
    storageBucket: 'elswhere-dev.appspot.com',
    iosBundleId: 'com.welike2coding.elswhere',
  );

  static const FirebaseOptions androidProd = FirebaseOptions(
    apiKey: 'AIzaSyDXB9w1f8lNjh1IgKkClUWZc-_xV77n_9w',
    appId: '1:420188564022:android:a62a3f06438ebcb5368697',
    messagingSenderId: '420188564022',
    projectId: 'elswhere-adaf5',
    storageBucket: 'elswhere-adaf5.appspot.com',
  );

  static const FirebaseOptions iosProd = FirebaseOptions(
    apiKey: 'AIzaSyBg9M181UgLKYRA-ohnlC4aMY_ivkkpky8',
    appId: '1:420188564022:ios:d57b165c64ee77cc368697',
    messagingSenderId: '420188564022',
    projectId: 'elswhere-adaf5',
    storageBucket: 'elswhere-adaf5.appspot.com',
    iosBundleId: 'com.welike2coding.elswhere',
  );
}
